### ISSUE TITLE
Startup crash with v4.1.9

### ISSUE THREAD

**Issue by MachineRat8** [d4rkm0nkey/HorseStatsVanilla#13]
Minecraft 1.18 crashes on startup, here is the crash log:
[crash-2021-12-05_18.37.54-client.txt](https://github.com/d4rkm0nkey/HorseStatsVanilla/files/7656385/crash-2021-12-05_18.37.54-client.txt)
Fabric version: 0.12.8
Fabric API version: 0.43.1+1.18
Mod version: 4.1.9

**Comment by d4rkm0nkey** [comment]
Is this problem fixed with version 4.1.10?

**Comment by MachineRat8** [comment]
Yes, it's working now. Thank you!
