### ISSUE TITLE
Game Crashes using Fabric 1.19.4 and Optifabric

### ISSUE THREAD

**Issue by CodyCannoli** [d4rkm0nkey/HorseStatsVanilla#25]
Opening game shows "resource reload failed" popup on title screen

Crash Message:
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.setSampler(int, Object)" because "shaderinstance" is null

Game crashes while trying to use OptiFabric-v1.13.24 and OptiFine 1.19.4 HD U I4

Let me know if you need any more information

**Comment by d4rkm0nkey** [comment]
Are you trying to have both Optifabric and Optifine at the same time? The error log seems not to be connected to HorseStatsVanilla in any way. The `setSampler` method is not used by the mod. 
If you need further help, send me the full log of the crash.
You can also try to install the newest FabricApi version.

**Comment by Incompetenttwat** [comment]
What do you mean with 
> Are you trying to have both Optifabric and Optifine at the same time
I thought you need to have both, Optifine and optifabric in you mod folder?
