### ISSUE TITLE
Horse Stats Vanilla Bedrock

### ISSUE THREAD

**Issue by Abraxas08** [d4rkm0nkey/HorseStatsVanilla#26]
Can you help me to make this Mod for the Bedrock Version? I don't have any Experience with programming Minecraft Mods. But I would like a Mod like this for the Bedrock Version, thanks for an Answer.

**Comment by d4rkm0nkey** [comment]
I dont't think that it is possible to do so and if it is I sadly can't help you, because I know nothing about modding in Bedrock.
