### ISSUE TITLE
Version 4.2.3 Has Not Been Uploaded to Modrinth

### ISSUE THREAD

**Issue by IAmEchino** [d4rkm0nkey/HorseStatsVanilla#27]
I don't know if this was intentional, but I wanted to let y'all know just in case it wasn't.

**Comment by srnyx** [comment]
It has been now by the way: https://modrinth.com/mod/horsestatsvanilla/version/W1Cr0hgK

**Comment by d4rkm0nkey** [comment]
This is a good reminder for me to not forget uploading new version to Modrinth haha.
Should really set up the auto publish feature :D

**Comment by srnyx** [comment]
> Should really set up the auto publish feature :D

👀 https://github.com/Kir-Antipov/mc-publish
