### ISSUE TITLE
Incompatible with 1.20

### ISSUE THREAD

**Issue by Kichura** [d4rkm0nkey/HorseStatsVanilla#35]
[Crash logs can be found here.](https://pastebin.com/raw/fPgVEBSK) - While updating LibGui solves the instant-boot crash, right-clicking any horse entity will crash on post-update instead.

**Comment by Kichura** [comment]
Update: Closing this issue due to [this fork](https://github.com/NotGeri/HorseStatsVanilla) resolving my issue.

**Comment by upcomingshoes** [comment]
As of last night, I had this crash as well, from the version downloaded both via Modrinth and CurseForge - specifically, the right-clicking on horse entity crash. Each site said the file was updated 6/14 and was version 4.4.0.

If that new fork solves the issue, will it be uploaded to Curse/Mod soon?

Thank you!
